
import { Story, Translation, Language, CATEGORIES, AGE_GROUPS } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  tr: {
    welcome: "Masalya'ya Hoşgeldin",
    welcomeDesc: "Sihirli hikayeler dünyasını keşfet",
    home: "Keşfet",
    create: "Oluştur",
    profile: "Profilim",
    categories: "Kategoriler",
    classics: "Klasik Masallar",
    generated: "İşte Yeni Masalın",
    readNow: "Hemen Oku",
    createTitle: "Kendi Masalını Yaz",
    createDesc: "Aklındakileri yaz, Masalya senin için sihirli bir masal anlatsın.",
    promptPlaceholder: "Örn: Ormanda kaybolan yavru bir ayı...",
    generateBtn: "Masal Oluştur",
    generating: "Hikaye Yazılıyor...",
    darkMode: "Karanlık Mod",
    lightMode: "Aydınlık Mod",
    ageGroup: "Yaş Grubu",
    allAges: "Tümü",
    favorites: "Favorilerim",
    storiesRead: "Okunan Masallar",
    myStories: "Oluşturduğum Masallar",
    noStoriesYet: "Henüz bir masal yok.",
    tryCreating: "Yeni oluşturmayı dene!",
    back: "Geri",
    save: "Kaydet",
    delete: "Sil",
    saved: "Kaydedildi",
    yearsOld: "Yaş",
    endOfStory: "Masalın Sonu",
    cat_adventure: "Macera",
    cat_fantasy: "Fantastik",
    cat_animals: "Hayvanlar",
    cat_bedtime: "Uyku Vakti",
    cat_folk: "Halk Masalları",
    painting: "Resim Çiziliyor...",
    createMagicImage: "Sihirli Resim Oluştur",
    magicImageCreated: "Resim Oluşturuldu!"
  },
  en: {
    welcome: "Welcome to Masalya",
    welcomeDesc: "Discover a world of magical stories",
    home: "Discover",
    create: "Create",
    profile: "Profile",
    categories: "Categories",
    classics: "Classic Tales",
    generated: "Here is Your Story",
    readNow: "Read Now",
    createTitle: "Write Your Own Tale",
    createDesc: "Enter a few words and let AI weave a magical story for you.",
    promptPlaceholder: "Ex: A brave cat going to space...",
    generateBtn: "Generate Story",
    generating: "Writing Story...",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    ageGroup: "Age Group",
    allAges: "All",
    favorites: "My Favorites",
    storiesRead: "Stories Read",
    myStories: "My Created Stories",
    noStoriesYet: "No stories yet.",
    tryCreating: "Try creating one!",
    back: "Back",
    save: "Save",
    delete: "Delete",
    saved: "Saved",
    yearsOld: "Years",
    endOfStory: "The End",
    cat_adventure: "Adventure",
    cat_fantasy: "Fantasy",
    cat_animals: "Animals",
    cat_bedtime: "Bedtime",
    cat_folk: "Folk Tales",
    painting: "Painting Picture...",
    createMagicImage: "Create Magic Image",
    magicImageCreated: "Image Created!"
  }
};

export const STATIC_STORIES: Story[] = [
  {
    id: 's1',
    title: 'Keloğlan ve Sihirli Tas',
    content: "Bir varmış, bir yokmuş. Evvel zaman içinde, kalbur saman içinde, uzak bir köyde Keloğlan yaşarmış. Annesiyle birlikte yaşayan Keloğlan, bir gün nehir kenarında parlayan bir tas bulmuş. Bu tas sıradan bir tas değilmiş, içine ne koyarsan bereketlenir, çoğalırmış. Keloğlan tası alıp eve götürmüş. Annesi, 'Oğlum bu ne?' diye sormuş. Keloğlan, 'Ana, bu sihirli bir tas, artık aç kalmayacağız' demiş. Ancak köyün açgözlü ağası bunu duymuş ve tası almak istemiş. Keloğlan zekasını kullanarak ağaya bir ders vermiş. Ağa tası zorla aldığında, tasın içinden yemek yerine kurbağalar çıkmış! Keloğlan, dürüstlüğün ve zekanın her zaman kazandığını bir kez daha kanıtlamış.",
    category: CATEGORIES.FOLK,
    ageGroup: AGE_GROUPS.KID,
    imageUrl: 'https://picsum.photos/400/300?random=1',
    isAiGenerated: false,
    author: 'Anonim',
    language: 'tr',
    createdAt: 1715000000000
  },
  {
    id: 's2',
    title: 'The Lion and the Mouse',
    content: "Once when a Lion was asleep a little Mouse began running up and down upon him; this soon wakened the Lion, who placed his huge paw upon him, and opened his big jaws to swallow him. 'Pardon, O King,' cried the little Mouse: 'forgive me this time, I shall never forget it: who knows but what I may be able to do you a turn some of these days?' The Lion was so tickled at the idea of the Mouse being able to help him, that he lifted up his paw and let him go. Some time after the Lion was caught in a trap, and the hunters who desired to carry him alive to the King, tied him to a tree while they went in search of a waggon to carry him on. Just then the little Mouse happened to pass by, and seeing the sad plight in which the Lion was, went up to him and soon gnawed away the ropes that bound the King of the Beasts. 'Was I not right?' said the little Mouse.",
    category: CATEGORIES.ANIMALS,
    ageGroup: AGE_GROUPS.TODDLER,
    imageUrl: 'https://picsum.photos/400/300?random=2',
    isAiGenerated: false,
    author: 'Aesop',
    language: 'en',
    createdAt: 1715000000000
  },
  {
    id: 's3',
    title: 'Kırmızı Başlıklı Kız',
    content: "Bir zamanlar, ormanın kenarındaki küçük bir köyde, herkesin çok sevdiği tatlı bir kız yaşarmış. Büyükannesi ona kırmızı kadifeden bir başlık dikmişti ve o kadar yakışmıştı ki, o günden sonra herkes ona 'Kırmızı Başlıklı Kız' demeye başlamış. Bir gün annesi, 'Kırmızı Başlıklı Kız, al bu keki ve şarabı büyükannene götür' demiş. Ormanda yürürken kurnaz bir kurtla karşılaşmış. Kurt, kızı kandırıp yolu uzatmış ve büyükannenin evine ondan önce varmış. Ancak ormancı durumu fark edip kurdu yakalamış ve hem büyükneyi hem de Kırmızı Başlıklı Kızı kurtarmış. O günden sonra Kırmızı Başlıklı Kız, annesinin sözünden hiç çıkmamış.",
    category: CATEGORIES.ADVENTURE,
    ageGroup: AGE_GROUPS.KID,
    imageUrl: 'https://picsum.photos/400/300?random=3',
    isAiGenerated: false,
    author: 'Grimm Kardeşler',
    language: 'tr',
    createdAt: 1715000000000
  },
  {
    id: 's4',
    title: 'The Ugly Duckling',
    content: "It was so beautiful out in the country. It was summer-time. The wheat was yellow, the oats were green, the hay was stacked up in the grassy meadows, and the stork paraded about on his long red legs. In a sunny spot stood a pleasant old farm-house close by a deep river. In this snug retreat sat a duck on her nest, watching for her young brood to hatch. Finally, the eggs cracked and out came ducklings. But one egg was larger than the rest. When it hatched, the duckling was grey and ugly. Everyone teased him. He ran away and spent a lonely winter. But when spring came, he saw beautiful swans in the lake. He flew to them, expecting them to peck him, but instead, they bowed to him. He looked at his reflection in the water and saw that he was no longer an ugly duckling, but a beautiful swan!",
    category: CATEGORIES.ANIMALS,
    ageGroup: AGE_GROUPS.KID,
    imageUrl: 'https://picsum.photos/400/300?random=4',
    isAiGenerated: false,
    author: 'Hans Christian Andersen',
    language: 'en',
    createdAt: 1715000000000
  }
];